app:
  frontend:
    url: ${FRONTEND_URL:https://localhost:5173}

server:
  port: 8443
  ssl:
    key-store: ${SSL_KEY_STORE:classpath:keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:dbcase_ssl}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:dbcase}

spring:
  application:
    name: DBCaseWeb
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/dbcase}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
jwt:
  secret: ${JWT_SECRET:SsXhO9cPI5berPvVYKr9ylOF1q0Z9snw/EzEhfwN0VY=}

#logging:
#  level:
#    org.springframework.web: DEBUG