services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: DBCaseApp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbcase
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_USER}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:17.9-alpine3.23'
    container_name: DBCaseDB
    ports:
      - "5432:5432"
    volumes:
      - dbcaseDB:/var/lib/postgresql/data
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_DB=dbcase
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  dbcaseDB: