/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUsDialog: typeof import('./src/components/dialogs/AboutUsDialog.vue')['default']
    AccessibilityDialog: typeof import('./src/components/dialogs/AccessibilityDialog.vue')['default']
    AddEntityDialog: typeof import('./src/components/dialogs/AddEntityDialog.vue')['default']
    AddRelationshipDialog: typeof import('./src/components/dialogs/AddRelationshipDialog.vue')['default']
    AttributeNode: typeof import('./src/components/canvas/nodes/AttributeNode.vue')['default']
    Button: typeof import('primevue/button')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CommandTable: typeof import('./src/components/CommandTable.vue')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DiagramCanvas: typeof import('./src/components/canvas/DiagramCanvas.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EntityNode: typeof import('./src/components/canvas/nodes/EntityNode.vue')['default']
    ERDiagram: typeof import('./src/components/ERDiagram.vue')['default']
    ErrorTemplate: typeof import('./src/components/ErrorTemplate.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    GenerateSchemeDialog: typeof import('./src/components/dialogs/GenerateSchemeDialog.vue')['default']
    HelpDialog: typeof import('./src/components/dialogs/HelpDialog.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayoutDialog: typeof import('./src/components/dialogs/LayoutDialog.vue')['default']
    Message: typeof import('primevue/message')['default']
    OpenSchemaDialog: typeof import('./src/components/dialogs/OpenSchemaDialog.vue')['default']
    PanelDBScheme: typeof import('./src/components/panels/PanelDBScheme.vue')['default']
    PanelERScheme: typeof import('./src/components/panels/PanelERScheme.vue')['default']
    PanelLogicalScheme: typeof import('./src/components/panels/PanelLogicalScheme.vue')['default']
    ProfileData: typeof import('./src/components/ProfileData.vue')['default']
    RelationshipNode: typeof import('./src/components/canvas/nodes/RelationshipNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveSchemaDialog: typeof import('./src/components/dialogs/SaveSchemaDialog.vue')['default']
    Select: typeof import('primevue/select')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
